version: '3.8'

services:
  ui:
    build:
      context: .
      target: build
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080